services:
    # Application service
    postgres:
        build:
            context: ./docker/postgres
            dockerfile: Dockerfile
        environment:
            POSTGRES_DB: fantasy_characters_dev
            POSTGRES_USER: fantasy_user
            POSTGRES_PASSWORD: fantasy_password
            POSTGRES_INITDB_ARGS: '--encoding=UTF8 --locale=C'
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./docker/postgres/init:/docker-entrypoint-initdb.d
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U fantasy_user -d fantasy_characters_dev']
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 30s
        restart: unless-stopped
        networks:
            - fantasy_network

    # For development convenience - PostgreSQL admin interface
    pgadmin:
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@fantasy-api.dev
            PGADMIN_DEFAULT_PASSWORD: admin123
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        ports:
            - '8080:80'
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        depends_on:
            postgres:
                condition: service_healthy
        restart: unless-stopped
        networks:
            - fantasy_network
        profiles:
            - admin

volumes:
    postgres_data:
        driver: local
    pgadmin_data:
        driver: local

networks:
    fantasy_network:
        driver: bridge
